name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  test:
    uses: "./.github/workflows/test.yml"
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - name: "Pip dependencies"
        run : |
          python -m pip install -r requirements.txt
      - name: "Run sdist"
        run: |
          python setup.py sdist --formats=zip,gztar
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "PyTower ${{ github.ref_name }}"
          prerelease: true
          files: |
            dist/*.zip
            dist/*.tar.gz