name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  test:
    uses: "./.github/workflows/test.yml"
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    permissions: write-all

    steps:
      - uses: actions/checkout@v3
      - name: "Pip dependencies"
        run : |
          python -m pip install -r requirements.txt
      - name: "Run sdist"
        run: |
          python setup.py sdist --formats=zip bdist_wheel
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "lite-sandbox ${{ github.ref_name }}"
          prerelease: false
          files: |
            dist/*.zip
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
